@startuml zustandsdiagramm_abgemeldet
skinparam Dpi 400
hide empty description

title UML-Zustandsdiagramm für den "Page Flow" bei einem abgemeldeten Benutzer
caption (c) Botan Coban, Felix Jäger, Philip Neuffer

state "index.html" as index {

state Suche{

    [*] --> Suchformular
    Suchformular --> Suchformular : Suchkriterien eingeben
    note "Clientseitige Validierung" as note
    Suchformular --> note

    Suchformular --> Waiting: Button "OK"

    state Suchergebnis{
        state c <<choice>>
        [*] --> c : Prüfung
        c --> Fehlermeldung: Kein Buch gefunden
        c --> GefundeneBuecher: Mind. 1 Buch gefunden
        GefundeneBuecher --> DetailsBuch : Buch ausgewählt
    }

    Waiting --> Suchergebnis : Suchergebnis eingetroffen
}

[*] --> Suche: Button "Suchen"
[*] -left-> Anmeldung: Button "Anmelden"

note "Home" as note2
[*] -right-> note2
}

@enduml
