@startuml zustandsdiagramm_angemeldet

hide empty description

title UML-Zustandsdiagramm für den "Page Flow" bei einem angemeldeten Benutzer
caption (c) Botan Coban, Felix Jäger, Philip Neuffer

state "index.html" as index {
index : jwt
index : roles
index : expiration

state Suche{

    [*] --> Suchformular : Suchkriterien eingeben

    Suchformular --> Waiting: Button "Suchen"

    state Suchergebnis{
        state c <<choice>>
        [*] --> c : Prüfung
        c --> Fehlermeldung: Kein Buch gefunden
        c --> GefundeneBuecher: Mind. 1 Buch gefunden
        GefundeneBuecher --> DetailsBuch : Buch ausgewählt
    }

    Waiting --> Suchergebnis : Suchergebnis eingetroffen
}

state Neuanlegen {
    state c2 <<choice>>

    [*] --> Eingabeformular : Daten eingeben

    Eingabeformular --> c2: Button "OK"
    c2 -up-> Eingabeformular: Fehlerhafte Daten

    c2 --> [*]: Korrekte Daten
}

[*] --> Suche: Button "Suche"
[*] --> Neuanlegen: Button "Neuanlegen"

[*] --> Home: Button "Logout"

Neuanlegen --> Home

}

@enduml
